### PR TITLE
[Fix] Panic when using npm start on OSX fresh dev setup. Resolves #1017.

### LINKED ISSUE #1017: [Bug] Panic with npm start on OSX fresh dev environment.
Branch: master
OS: Sierra 10.12.6

Reproduce: 
- ensure `~/Library/Preferences/Soundnode` does not exist
- clone soundnode-app master
- `cd soundnode-app && npm install`
- `npm start`

You will get an error dialogue like this:
screen shot 2017-10-06 at 4 01 31 pm

I have submitted a pr to fix it #1016

### PR DESCRIPTION
**Pull request by JackMordaunt**
Panic occurs when the path ~/Library/Preferences/Soundnode does not exist (ie a fresh dev setup) since `getUserConfig()` uses `fs.statSync(..)`, which throws an exception instead of returning an error if the directory does not exist.

If the directory mentioned above does exist, all is fine. When it doesn't, such as on a fresh dev setup, every time you run 'npm start' you get a panic and the app crashes.

My solution to this is to wrap `fs.statSync(..)` in a try catch and problem solved.

Furthermore I added in a guard which checks the type of `userConfigPath`. The reason for this guard is so we can throw a useful exception rather than a generic undefined or null exception.

### CODE REVIEW

File: app/public/js/common/configLocation.js [hunk 1]
```diff
@@ -38,12 +38,26 @@ const configuration = {
...
     // create user config in path
     // if there is no userConfig path
-    if (!fs.statSync(userConfigPath).isDirectory()) {
-      this.createUserConfig()
+    //
+    // fs.statSync will throw an exception if
+    // any directory along the path doesn't exist.
+    // Solution: use try catch.
+    try {
+      var fi = fs.statSync(userConfigPath);
```
Comment (weblancaster) [inline app/public/js/common/configLocation.js]: can you rename the variable to something more clear please?

File: app/public/js/common/configLocation.js [hunk 2]
```diff
@@ -38,12 +38,26 @@ const configuration = {
       userConfigPath = `${userHome}/Library/Preferences/Soundnode`;
     }
 
+    // Guard to assert type of string.
+    if (typeof userConfigPath !== "string") {
```
Comment (weblancaster) [inline app/public/js/common/configLocation.js]: can you tell me if there is a specific case for this check to be necessary? thanks

File: app/public/js/common/configLocation.js [hunk 3]
```diff
@@ -38,12 +38,26 @@ const configuration = {
...
+
     // create user config in path
     // if there is no userConfig path
-    if (!fs.statSync(userConfigPath).isDirectory()) {
-      this.createUserConfig()
+    //
+    // fs.statSync will throw an exception if
+    // any directory along the path doesn't exist.
+    // Solution: use try catch.
+    try {
```
Comment (weblancaster) [inline app/public/js/common/configLocation.js]: what are other solutions instead `try` `catch`?

**Comment by weblancaster** [comment]
@JackMordaunt thanks for contributing and sorry for my delay in reply to you.

can you take a look the comments I left please? thanks.

File: app/public/js/common/configLocation.js (hunk 3 above)
Comment (jakejarrett) [reply app/public/js/common/configLocation.js]: @weblancaster It appears `stat` throws an error, so we will need to catch the error or rethink the entire functionality of the configLocation

File: app/public/js/common/configLocation.js (hunk 2 above)
Comment (JackMordaunt) [reply app/public/js/common/configLocation.js]: Since `userConfigPath` is initially set to `null`, if the platform is not linux, windows, or darwin, then it never gets assigned to a `string`. Thus if `userConfigPath` is still a null value the platform is obviously not supported, so an exception is thrown to let the user know why the `userConfigPath` value could not be set properly.

File: app/public/js/common/configLocation.js (hunk 1 above)
Comment (JackMordaunt) [reply app/public/js/common/configLocation.js]: Given the tiny scope of the variable I felt the name to be adequate.
What would you consider to be a more clear name? Maybe something like `configFileInfo`?

Comment (jakejarrett) [reply app/public/js/common/configLocation.js]: `configFileInfo` would be more explicit,

Since the variable is never mutated, could you change it to a constant?

**Comment by jakejarrett** [comment]
this looks good to me, any concerns about merging @weblancaster ?

**Comment by jakejarrett** [comment]
@weblancaster Going to merge this so we can get a new release out.

**Comment by weblancaster** [comment]
@jakejarrett the code looks good but have you test before merging? if so and worked as expected no worries.
Otherwise will are taking a risk without testing.

**Comment by jakejarrett** [comment]
Yeah tested on Windows, Linux & Mac OSX.
